logging:
  level:
    org.hibernate.SQL: "TRACE"

spring:
  application:
    name: "chatapp"

  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: "update"

    open-in-view: false

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  output:
    ansi:
      enabled: "ALWAYS"

  servlet:
    multipart:
      enabled: true
      max-file-size: "100MB"
      max-request-size: "150MB"
      file-size-threshold: "2KB"
  quartz:
    job-store-type: jdbc   # Lưu job vào DB
    jdbc:
      initialize-schema: always   # Tạo bảng quartz_* nếu chưa có
    properties:
      org:
        quartz:
          jobStore:
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            isClustered: false
          dataSource:
            quartzDataSource:
              driver: com.mysql.cj.jdbc.Driver
              URL: "${DB_URL}"
              user: "${DB_USERNAME}"
              password: "${DB_PASSWORD}"
              maxConnections: 10

server:
  port: "${PORT:8000}"

jwts:
  public-key: "classpath:certs/jwts/public.pem"
  private-key: "classpath:certs/jwts/private.pem"

  access-token-lifetime: "PT30M" # 30 minutes
  refresh-token-lifetime: "P30D" # 30 days

  secret-key: "${JWT_SECRET}"

cloudinary:
  api-key: "${CLOUDINARY_API_KEY}"
  api-secret: "${CLOUDINARY_API_SECRET}"
  cloud-name: "${CLOUDINARY_CLOUD_NAME}"
