logging:
  level:
    org.hibernate.SQL: "TRACE"

spring:
  application:
    name: "chatapp"

  datasource:
    url: "jdbc:sqlite:db.sqlite3"
    driver-class-name: "org.sqlite.JDBC"

  jpa:
    hibernate:
      ddl-auto: "update"

    open-in-view: false

  output:
    ansi:
      enabled: ALWAYS

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB
      file-size-threshold: 2KB

server:
  port: "${PORT:8080}"

jwts:
  public-key: "classpath:certs/jwts/public.pem"
  private-key: "classpath:certs/jwts/private.pem"

  access-token-lifetime: PT30M # 30 minutes
  refresh-token-lifetime: P30D # 30 days

  secret-key: "${JWT_SECRET}"

cloudinary:
  cloud-name: ${webchat_cloud_name}
  api-key: ${webchat_api_key}
  api-secret: ${webchat_api_secret}